### ISSUE TITLE
Error at import time: `TypeError: 'classmethod' object is not subscriptable`

### ISSUE THREAD

**Issue by louismartin** [surge-ai/surge-python#83]
I'm getting the following error at import time with `surge-api==1.5.6` on linux and `python=3.10.14`
Error:
```
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import surge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda3/envs/dev3.10/lib/python3.10/site-packages/surge/__init__.py", line 3, in <module>
    from surge.projects import Project
  File "~/miniconda3/envs/dev3.10/lib/python3.10/site-packages/surge/projects.py", line 12, in <module>
    class Project(APIResource):
  File "~/miniconda3/envs/dev3.10/lib/python3.10/site-packages/surge/projects.py", line 159, in Project
    def list_shared(cls, page: int = 1, statuses: list[str] = [], api_key: str = None):
TypeError: 'classmethod' object is not subscriptable
```

**Comment by louismartin** [comment]
Removing the type hint `: list[str]` fixes the issue.

**Comment by louismartin** [comment]
It's most likely due to the classmethod called list defined just above:
```
    @classmethod
    def list(cls, page: int = 1, statuses: list[str] = [], api_key: str = None):
        '''
        Lists all projects you have created.
        Projects are returned in descending order of created_at.
        Each page contains a maximum of 100 projects.

        Arguments:
            page (int, optional): Page number to retrieve. Pages start at 1 (default value).

        Returns:
            projects (list): list of Project objects.
        '''
        params = {"page": page, "statuses": statuses}
        response_json = cls.get(PROJECTS_ENDPOINT, params, api_key=api_key)
        projects = [cls(**project_json) for project_json in response_json]
        return projects

    @classmethod
    def list_shared(cls, page: int = 1, statuses: list[str] = [], api_key: str = None):
        '''
        Lists all projects created by anyone in your organization.
        Projects are returned in descending order of created_at.
        Each page contains a maximum of 100 projects.

        Arguments:
            page (int, optional): Page number to retrieve. Pages start at 1 (default value).

        Returns:
            projects (list): list of Project objects.
        '''
        params = {"page": page, "statuses": statuses}
        endpoint = f"{PROJECTS_ENDPOINT}/shared"
        response_json = cls.get(endpoint, params, api_key=api_key)
        projects = [cls(**project_json) for project_json in response_json]
        return projects
```

(by the way, unless that's on purpose, it's generally not recommended to instantiate a list as a default arg)

**Comment by louismartin** [comment]
This seems to be due to https://github.com/surge-ai/surge-python/pull/82
